### PR TITLE
Fit fraction rework

### PR DESCRIPTION
**Pull request by spflueger**
This update brings back the fit fraction functionality! Now various fit fractions can be constructed, based on the name of the Amplitudes or Intensities. Some example code on how to use the new fit fraction functionality can be seen in the DalitzFitApp.

I made some rough comparison of the fit fraction results of the DalitzFitApp. But since a lot of things have changed since the fit fraction functionality was working, it is almost impossible to get a 100% match.

Let me know what you think. I will change the commit messages once we are closer to finalizing the pull request.

### CODE REVIEW

**Comment by zhang-jingqing** [comment]
Take the decay jpsi -> gamma f0, f0 -> pi pi for example, jpsi -> gamma f0 can be L = 0 S =1 or L = 2 S = 1; if there are two f0, f0(980) and f0(1500), can we get the 'resonance component' of f0(980) and f0(1500)? And can we get the 'wave component', L = 0 of f0(980) and f0(1500); and L = 2 of f0(980) and f0(1500)? 
A simplified model xml file looks like this:
<pre><font color="#2AA198">&lt;Intensity </font><font color="#859900">Class</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;NormalizedIntensity&quot;</font><font color="#2AA198"> </font><font color="#859900">Name</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;jpsi2gpipi&quot;</font><span style="background-color:#657B83"><font color="#2AA198">&gt;</font></span>                  <span style="background-color:#FFD7D7"> </span>
        <font color="#2AA198">&lt;Intensity </font><font color="#859900">Class</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;CoherentIntensity&quot;</font><font color="#2AA198"> </font><font color="#859900">Name</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;jpsi_1_to_g_1_pi_0_pi_0&quot;</font><span style="background-color:#FFD7D7"><font color="#2AA198">&gt;</font></span>
                <font color="#2AA198">&lt;Amplitude </font><font color="#859900">Class</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;CoefficientAmplitude&quot;</font><font color="#2AA198"> </font><font color="#859900">Name</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;jpsi_1_to_g_1</font><span style="background-color:#FFD7D7"><font color="#DC322F">_</font></span><font color="#DC322F">f0(980)_L_0_S_1&quot;</font><span style="background-color:#657B83"><font color="#2AA198">&gt;</font></span>
                <font color="#2AA198">&lt;/Amplitude</font><span style="background-color:#657B83"><font color="#2AA198">&gt;</font></span>                                                   <span style="background-color:#FFD7D7"> </span>
                <font color="#2AA198">&lt;Amplitude </font><font color="#859900">Class</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;CoefficientAmplitude&quot;</font><font color="#2AA198"> </font><font color="#859900">Name</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;jpsi_1_to_g_1</font><span style="background-color:#FFD7D7"><font color="#DC322F">_</font></span><font color="#DC322F">f0(980)_L_2_S_1&quot;</font><span style="background-color:#657B83"><font color="#2AA198">&gt;</font></span>
                <font color="#2AA198">&lt;/Amplitude</font><span style="background-color:#657B83"><font color="#2AA198">&gt;</font></span>                                                   <span style="background-color:#FFD7D7"> </span>
                <font color="#2AA198">&lt;Amplitude </font><font color="#859900">Class</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;CoefficientAmplitude&quot;</font><font color="#2AA198"> </font><font color="#859900">Name</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;jpsi_1_to_g_1</font><span style="background-color:#FFD7D7"><font color="#DC322F">_</font></span><font color="#DC322F">f0(1500)_L_0_S_1&quot;</font><span style="background-color:#657B83"><font color="#2AA198">&gt;</font></span>
                <font color="#2AA198">&lt;/Amplitude</font><span style="background-color:#657B83"><font color="#2AA198">&gt;</font></span>                                                   <span style="background-color:#FFD7D7"> </span>
                <font color="#2AA198">&lt;Amplitude </font><font color="#859900">Class</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;CoefficientAmplitude&quot;</font><font color="#2AA198"> </font><font color="#859900">Name</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;jpsi_1_to_g_1</font><span style="background-color:#FFD7D7"><font color="#DC322F">_</font></span><font color="#DC322F">f0(1500)_L_2_S_1&quot;</font><span style="background-color:#657B83"><font color="#2AA198">&gt;</font></span>
                <font color="#2AA198">&lt;/Amplitude</font><span style="background-color:#657B83"><font color="#2AA198">&gt;</font></span>                                                   <span style="background-color:#FFD7D7"> </span>
        <font color="#2AA198">&lt;/Intensity</font><span style="background-color:#657B83"><font color="#2AA198">&gt;</font></span>                                                           <span style="background-color:#FFD7D7"> </span>
        <font color="#2AA198">&lt;Intensity </font><font color="#859900">Class</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;CoherentIntensity&quot;</font><font color="#2AA198"> </font><font color="#859900">Name</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;jpsi_-1_to_g_-1_pi_0_pi_</font><span style="background-color:#FFD7D7"><font color="#DC322F">0</font></span><font color="#DC322F">&quot;</font><span style="background-color:#657B83"><font color="#2AA198">&gt;</font></span>
                <font color="#2AA198">&lt;Amplitude </font><font color="#859900">Class</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;CoefficientAmplitude&quot;</font><font color="#2AA198"> </font><font color="#859900">Name</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;jpsi_-1_to_g_</font><span style="background-color:#FFD7D7"><font color="#DC322F">-</font></span><font color="#DC322F">1_f0(980)_L_0_S_1&quot;</font><span style="background-color:#657B83"><font color="#2AA198">&gt;</font></span>
                <font color="#2AA198">&lt;/Amplitude</font><span style="background-color:#657B83"><font color="#2AA198">&gt;</font></span>                                                   <span style="background-color:#FFD7D7"> </span>
                <font color="#2AA198">&lt;Amplitude </font><font color="#859900">Class</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;CoefficientAmplitude&quot;</font><font color="#2AA198"> </font><font color="#859900">Name</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;jpsi_-1_to_g_</font><span style="background-color:#FFD7D7"><font color="#DC322F">-</font></span><font color="#DC322F">1_f0(980)_L_2_S_1&quot;</font><span style="background-color:#657B83"><font color="#2AA198">&gt;</font></span>
                <font color="#2AA198">&lt;/Amplitude</font><span style="background-color:#657B83"><font color="#2AA198">&gt;</font></span>                                                   <span style="background-color:#FFD7D7"> </span>
                <font color="#2AA198">&lt;Amplitude </font><font color="#859900">Class</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;CoefficientAmplitude&quot;</font><font color="#2AA198"> </font><font color="#859900">Name</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;jpsi_-1_to_g_</font><span style="background-color:#FFD7D7"><font color="#DC322F">-</font></span><font color="#DC322F">1_f0(1500)_L_0_S_1&quot;</font><span style="background-color:#657B83"><font color="#2AA198">&gt;</font></span>
                <font color="#2AA198">&lt;/Amplitude</font><span style="background-color:#657B83"><font color="#2AA198">&gt;</font></span>                                                   <span style="background-color:#FFD7D7"> </span>
                <font color="#2AA198">&lt;Amplitude </font><font color="#859900">Class</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;CoefficientAmplitude&quot;</font><font color="#2AA198"> </font><font color="#859900">Name</font><font color="#2AA198"> </font>=<font color="#2AA198"> </font><font color="#DC322F">&quot;jpsi_-1_to_g_</font><span style="background-color:#FFD7D7"><font color="#DC322F">-</font></span><font color="#DC322F">1_f0(1500)_L_2_S_1&quot;</font><span style="background-color:#657B83"><font color="#2AA198">&gt;</font></span>
                <font color="#2AA198">&lt;/Amplitude</font><span style="background-color:#657B83"><font color="#2AA198">&gt;</font></span>                                                   <span style="background-color:#FFD7D7"> </span>
        <font color="#2AA198">&lt;/Intensity</font><span style="background-color:#657B83"><font color="#2AA198">&gt;</font></span>                                                           <span style="background-color:#FFD7D7"> </span>
<font color="#2AA198">&lt;/Intensity</font><span style="background-color:#657B83"><font color="#2AA198">&gt;</font></span>               </pre>   

I would like to write a 'resonance component' as below:
//resonance components                                                          
ComponentList:                                                                  
= {                                                                             
  { //f0(980)                                                                   
    "jpsi_1_to_g_1_f0(980)_L_0_S_1", //coherent sum1                            
    "jpsi_1_to_g_1_f0(980)_L_2_S_1", //coherent sum1                            
    "jpsi_-1_to_g_-1_f0(980)_L_0_S_1", //coherent sum2                          
    "jpsi_-1_to_g_-1_f0(980)_L_2_S_1" //coherent sum2                           
  },                                                                            
  { //f0(1500)                                                                  
    "jpsi_1_to_g_1_f0(1500)_L_0_S_1",                                           
    "jpsi_1_to_g_1_f0(1500)_L_2_S_1",                                           
    "jpsi_-1_to_g_-1_f0(1500)_L_0_S_1",                                         
    "jpsi_-1_to_g_-1_f0(1500)_L_2_S_1"                                          
  }                                                                             
};   
And I think, code in BuilderXML.cpp in line 69, ComponentList.erase(...) will prevent building this kind of component. More over, code in BuilderXML.cpp in line 143-149 will build a coherent intensity, but for the above 'resonance component', it requires a mixed incoherent and coherent intensity.

**Comment by zhang-jingqing** [comment]
maybe it's better first get a subtree from the whole model tree by extracting the direct subtree of the NormalizeIntensityTree, then take this subtree as a component tree, and remove the nodes whose name is not contained in the component(vector<string>).

**Comment by spflueger** [comment]
Hi Jingqing, thanks for taking a look at the code. Did you try this example? It did not do any testing on this yet, but I thought that I implemented things in a general way that something like this is possible.

You just cant mix amplitudes and intensities, when you combine them to a total fraction.

**Comment by spflueger** [comment]
Ok, I improved the fit fraction code and fixed another open issue about the normalization with this pull request. Take a look at it and let me know what you think. CodeFactor is pointing out the the code in BuilderXML is quite complicated. I don't quite understand yet at which point he complains. I think it's the general complexity of the BuilderXML, that there is just too much functionality within this class...

I want to squash merge this pull request so please let me take care of the merging.

**Comment by spflueger** [comment]
So the complexity issue of CodeFactor is related to the complexity of the the IntensityBuilderXML. This class has the responsibility of creating a function tree intensity (and now also components). Yes the code is a bit lengthy because all of XML to FunctionTree code is in this cpp file. I don't see a problem with that though. The problem of the complexity arises from the handling of the normalizations. Currently this is solved by a State Structure in the class.
I ignored this issue in CodeFactor for now, because fixing this would be larger refactoring. We should improve the code in that regard though.

**Comment by weidenka** [comment]
In my case, specifying a non-existent component leads to a seg_fault. This should not happen.

**Comment by spflueger** [comment]
I reworked the IntensityBuilder a bit in one of the last commits to get rid of the state. Instead the data lists are passed with the functions recursively.

@weidenka 
- You asked me once to also fix the initialization of the Intensity from a list of FitParameter in this PR. Because the actual root of the problem is quite deep and it is a difficult task to solve nicely, it would require a lot of code changes that are way out of proportion for this PR. Hence it should be handled in a separate PR.
- Also I did not add your PR changes for the DalitzFit (#253). I think its best if you just apply those with your PR separately

**Pull request merged**
