### PR TITLE
new fit result struct proposal

### PR DESCRIPTION
**Pull request by spflueger**
This is my proposal for the rework of the fit result classes. Its not finished, but it should give an idea how it works. If we decide to use this I will finish this up

### CODE REVIEW

**Comment by spflueger** [comment]
Here is a list of pro and cons of this approach:
Pro:
- `FitResult` is a pure data structure, which means that adding new functions working with `FitResult` structs is easy. Theoretically, the downside of pure data structures are that adding new members to `FitResult` would require the modification of all functions working with `FitResult`. However, the `std::map` structure allows for flexibility of adding new members, and only changes in functions where these new members are required. So this downside is pretty much eliminated (especially if one uses std::any/std::variant but that requires c++17)
- possibility to dynamically add information/properties to the `FitResult`
- only information, which is actually present is inside the `FitResult` (no empty/uninitialized fields)
- All optimizers return the same `FitResult` structure, which does not require any casting
- All optimizer instances only have to fill the `FitResult` and do not have to create a new inherited `FitResult` (avoids overuse of inheritance)

Cons:
- Compiler cannot detect wrong access to the `std::map` containers, which can result in runtime errors or weird behavior, unless some safety feature like a getter and setter are used.

**Comment by zhang-jingqing** [comment]
It sounds good. I hope I can access parameters' name/values/errors/error matrix 
and fit status (edm, -logL, minimum valid or not, converged or not, error matrix valid or not etc.).
I think we also need to care how to load a such fit result to the specific in used, e.g., load fit result to recover a minuit2 fit result. (I am not sure if this feature will be used or not. If it will be never used, 
we can skip this).

**Comment by spflueger** [comment]
Do you think it would be better to use inheritance here? So we have a base class `FitResult` and add more properties as needed by inheriting from that.
And do you think it is still comprehensible or transparent to a developer and user what is stored inside the FitResult?

**Comment by hansgans** [comment]
I do not agree with the proposed change. The huge disadvantage is that the content of `std::map` in `FitResult.hpp` is not known at compile time. Which has several disadvantages:
* A proper writen CPP application would need to encapsulate each call to those `std::map`'s in a `try...catch` statement (that might be fine in python)
* A dynamical approach is not nessessary since the optimizer interfaces is not dynamic
* Given you write CPP code. Where do you find the information whats under which name is stored? It is not automatically documented via doxygen and you can not document it in the `FitResults.hpp`, the place where you would expect such an information. Since the content is not known to the compiler you can not use tab completition in your IDE.

So I propose to stick with an inheritance pattern:
```
class FitResult
{
    inital, final parameters
}
class MinuitResult : public FitResult 
{
    minos, hesse information
}
```

**Comment by spflueger** [comment]
> A proper writen CPP application would need to encapsulate each call to those std::map's in a try...catch statement (that might be fine in python)

I don't see that as a "huge" disadvantage.

> A dynamical approach is not nessessary since the optimizer interfaces is not dynamic

This is not a disadvantage. If its anything it is an advantage.

I definitely prefer the `struct` solution with `std::map`, for the reasons I listed above (and there might be even more). Let me make a small example of a disadvantage of the inheritance solution:

Let's say there is some property `X`, which is not inside the base class `FitResult`. If there is some function which performs some task using this property `X`, you need to give this function an instance of inherited FitResults which have this property `X` defined. However if this property `X` is defined in many different inherited FitResult types, then you need to copy this function for each of these types.
You can of course decide to make this property `X` something "common" and put it inside the base class. But then some Optimizers might not use this property and it will be unset. This is not good and a nice example of when **not** to use inheritance (for example: https://softwareengineering.stackexchange.com/questions/12439/code-smell-inheritance-abuse). So you are stuck with writing multiple functions.

Also since we expose the `FitResult` to the python interface, it is much easier if this is just a simple data structure like proposed here (I think I don't need to elaborate this part)

**Comment by hansgans** [comment]
The first answer in your post suggests inheritance for a comparable problem.

**Comment by spflueger** [comment]
Was solved in #197

**Pull request closed without merging**
